# kotlinx-serialization
# Keep serializer classes generated by the compiler plugin
-keepclassmembers class cloud.osasoft.dartzvibe.data.model.** {
    *** Companion;
    *** INSTANCE;
}
-keep,includedescriptorclasses class cloud.osasoft.dartzvibe.data.model.**$$serializer { *; }
-keepclasseswithmembers class cloud.osasoft.dartzvibe.data.model.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Ktor OkHttp engine - loaded via ServiceLoader
-keep class io.ktor.client.engine.okhttp.OkHttpEngineContainer

# Voyager screen classes - serialized for process death restoration
# Screens with constructor parameters must keep their constructors
-keep class cloud.osasoft.dartzvibe.ui.screen.** extends cafe.adriel.voyager.core.screen.Screen {
    <init>(...);
}
